import coreWebVitals from 'eslint-config-next/core-web-vitals'

/*
 * ESLint flat config.
 *
 * Replaces `.eslintrc.json` and the `next lint` command, both of which Next 16
 * removed. `eslint-config-next@16` ships its `core-web-vitals` entry as a flat
 * array already, so this is a spread rather than a compat shim.
 *
 * IGNORES ARE NOT INHERITED ANY MORE. `next lint` knew to skip `.next` and the
 * build output; flat config does not, and `.eslintignore` is no longer read at
 * all. Everything the old command skipped has to be listed here or the first
 * run lints generated bundles and a nested worktree's node_modules.
 */
const config = [
  {
    ignores: [
      '.next/**',
      'out/**',
      'build/**',
      'next-env.d.ts',
      /* Local Claude worktrees carry their own node_modules. */
      '.claude/worktrees/**',
      /* Generated by Payload; not ours to lint. */
      'src/app/(payload)/admin/importMap.js',
      'src/payload-types.ts',
    ],
  },
  ...coreWebVitals,
  {
    rules: {
      /* Carried over from .eslintrc.json. */
      '@next/next/no-html-link-for-pages': 'off',
    },
  },
]

export default config
