#!/usr/bin/env bash
# Cloud Agent start: per-boot runtime initialization.
# Brings up a local PostgreSQL instance (owned by the agent user) and ensures
# the application database, role, and .env.local exist. Idempotent and
# restart-tolerant.
set -euo pipefail

PGBIN="$(ls -d /usr/lib/postgresql/*/bin | sort -V | tail -1)"
PGDATA="${PGDATA:-$HOME/.local/pgdata}"
PGPORT="${PGPORT:-5432}"
PGLOG="$HOME/.local/pg.log"
DB_NAME="amware"
DB_USER="amware"
DB_PASS="amware"

export PATH="$PGBIN:$PATH"

echo "==> Ensuring PostgreSQL data directory at $PGDATA"
if [ ! -s "$PGDATA/PG_VERSION" ]; then
  mkdir -p "$PGDATA"
  initdb -D "$PGDATA" -U postgres --auth-local=trust --auth-host=trust >/dev/null
fi

echo "==> Ensuring PostgreSQL server is running on port $PGPORT"
if ! pg_ctl -D "$PGDATA" status >/dev/null 2>&1; then
  pg_ctl -D "$PGDATA" -l "$PGLOG" -o "-p $PGPORT -k /tmp" -w start
fi

# Wait for readiness before issuing SQL.
for _ in $(seq 1 30); do
  if pg_isready -h 127.0.0.1 -p "$PGPORT" -q; then break; fi
  sleep 1
done

echo "==> Ensuring role and database exist"
psql -h 127.0.0.1 -p "$PGPORT" -U postgres -d postgres -tAc \
  "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" | grep -q 1 || \
  psql -h 127.0.0.1 -p "$PGPORT" -U postgres -d postgres -c \
  "CREATE ROLE $DB_USER LOGIN PASSWORD '$DB_PASS' SUPERUSER"

psql -h 127.0.0.1 -p "$PGPORT" -U postgres -d postgres -tAc \
  "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1 || \
  psql -h 127.0.0.1 -p "$PGPORT" -U postgres -d postgres -c \
  "CREATE DATABASE $DB_NAME OWNER $DB_USER"

echo "==> Ensuring .env.local exists for local development"
ENV_FILE="/workspace/.env.local"
if [ ! -f "$ENV_FILE" ]; then
  SECRET="$(openssl rand -hex 32)"
  cat > "$ENV_FILE" <<EOF
# Generated by .cursor/start.sh for local Cloud Agent development.
NEXT_PUBLIC_SITE_URL=http://localhost:3000
DATABASE_URI=postgres://$DB_USER:$DB_PASS@127.0.0.1:$PGPORT/$DB_NAME
PAYLOAD_SECRET=$SECRET
EOF
fi

echo "==> start.sh complete (PostgreSQL ready on port $PGPORT)"
