/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    users: User
    media: Media
    articles: Article
    projects: Project
    products: Product
    courses: Course
    lessons: Lesson
    services: Service
    'contact-submissions': ContactSubmission
    purchases: Purchase
    'payload-kv': PayloadKv
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {}
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    articles: ArticlesSelect<false> | ArticlesSelect<true>
    projects: ProjectsSelect<false> | ProjectsSelect<true>
    products: ProductsSelect<false> | ProductsSelect<true>
    courses: CoursesSelect<false> | CoursesSelect<true>
    lessons: LessonsSelect<false> | LessonsSelect<true>
    services: ServicesSelect<false> | ServicesSelect<true>
    'contact-submissions':
      | ContactSubmissionsSelect<false>
      | ContactSubmissionsSelect<true>
    purchases: PurchasesSelect<false> | PurchasesSelect<true>
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>
    'payload-preferences':
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>
    'payload-migrations':
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: number
  }
  fallbackLocale: null
  globals: {
    'pricing-page': PricingPage
  }
  globalsSelect: {
    'pricing-page': PricingPageSelect<false> | PricingPageSelect<true>
  }
  locale: null
  widgets: {
    collections: CollectionsWidget
  }
  user: User
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  sessions?:
    | {
        id: string
        createdAt?: string | null
        expiresAt: string
      }[]
    | null
  password?: string | null
  collection: 'users'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number
  alt?: string | null
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number
  title: string
  slug: string
  slugLock?: boolean | null
  publishedDate: string
  author?: string | null
  description?: string | null
  keywords?:
    | {
        keyword: string
        id?: string | null
      }[]
    | null
  canonical?: string | null
  ogImage?: (number | null) | Media
  coverImage?: (number | null) | Media
  content?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  /**
   * Links this entry to its file-based MDX article.
   */
  mdxSlug?: string | null
  status?: ('draft' | 'published') | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number
  name: string
  description?: string | null
  link?: {
    url?: string | null
    label?: string | null
  }
  logo?: (number | null) | Media
  order?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number
  name: string
  slug: string
  slugLock?: boolean | null
  type: 'digital' | 'boilerplate' | 'service-package'
  tagline?: string | null
  /**
   * Which column of the pricing page this kit belongs to. Kits only.
   */
  stack?: ('react-netsuite' | 'next-netsuite') | null
  /**
   * Which row. Sets the order the cards appear in.
   */
  tier?: ('lite' | 'pro' | 'team') | null
  /**
   * Frames this tier as the recommended one. Only the first is used, so marking everything popular marks nothing.
   */
  popular?: boolean | null
  /**
   * The short bullets on the pricing card — six or so, one line each. Separate from Features on purpose: the product page sells the kit, this column sells the difference between tiers.
   */
  pricingHighlights?:
    | {
        highlight: string
        id?: string | null
      }[]
    | null
  description?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  features?:
    | {
        feature: string
        id?: string | null
      }[]
    | null
  techStack?:
    | {
        tech: string
        id?: string | null
      }[]
    | null
  /**
   * Creem prod_… id. Absence ⇒ not purchasable. Editing this auto-fills the price from Creem.
   */
  creemProductId?: string | null
  price?: number | null
  /**
   * How many GitHub accounts this licence may invite. 1 for Lite and Pro, 5 for Team. The seat page refuses the seat past this number, so it is the licence, not a label.
   */
  seats?: number | null
  currency?: string | null
  /**
   * e.g. "one-time", "from"
   */
  priceLabel?: string | null
  heroImage?: (number | null) | Media
  /**
   * Optional 1200 × 630 social preview. Falls back to edition artwork for WareKit, or the product hero image and AMWare branding for other products.
   */
  ogImage?: (number | null) | Media
  gallery?:
    | {
        image?: (number | null) | Media
        id?: string | null
      }[]
    | null
  /**
   * owner/repo — reserved for the future GitHub-invite phase.
   */
  githubRepo?: string | null
  demoUrl?: string | null
  /**
   * Deliverable for digital downloads.
   */
  downloadFile?: (number | null) | Media
  /**
   * Alternative external deliverable URL.
   */
  downloadUrl?: string | null
  featured?: boolean | null
  order?: number | null
  status?: ('draft' | 'published') | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number
  title: string
  slug: string
  slugLock?: boolean | null
  summary?: string | null
  description?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  coverImage?: (number | null) | Media
  level?: ('beginner' | 'intermediate' | 'advanced') | null
  /**
   * Creem prod_… id. Absence ⇒ not purchasable. Editing this auto-fills the price from Creem.
   */
  creemProductId?: string | null
  price?: number | null
  featured?: boolean | null
  order?: number | null
  status?: ('draft' | 'published') | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number
  title: string
  /**
   * Used as the on-page anchor id.
   */
  slug?: string | null
  slugLock?: boolean | null
  course: number | Course
  /**
   * Grouping label; lessons are grouped by this on the course page.
   */
  module?: string | null
  order?: number | null
  content?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  videoUrl?: string | null
  durationMinutes?: number | null
  isPreview?: boolean | null
  status?: ('draft' | 'published') | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number
  name: string
  slug: string
  slugLock?: boolean | null
  summary?: string | null
  description?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  icon?: (number | null) | Media
  startingPrice?: number | null
  /**
   * What the price is per — "per month" for a retainer. Empty reads as a one-off. Without it a $3,000 monthly retainer renders as a flat $3,000, which is a very different offer.
   */
  priceLabel?: string | null
  /**
   * Rough time, e.g. "about 10 hrs a month".
   */
  commitment?: string | null
  /**
   * Cal.com link. Present ⇒ the card asks for an intro call instead of a quote, which is how a retainer actually starts.
   */
  bookingUrl?: string | null
  /**
   * The money line under the call to action — the deposit and what happens to it. Anything quoted here is a commitment to a client, so it lives with the tier it applies to rather than in a layout.
   */
  depositNote?: string | null
  /**
   * Creem prod_… id for a fixed-price package. Absence ⇒ "Request a quote".
   */
  creemProductId?: string | null
  whopPlanId?: string | null
  depositAmount?: number | null
  order?: number | null
  status?: ('draft' | 'published') | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number
  name: string
  email: string
  subject?: string | null
  message: string
  status?: ('new' | 'read' | 'archived') | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchases".
 */
export interface Purchase {
  id: number
  email: string
  item?:
    | ({
        relationTo: 'products'
        value: number | Product
      } | null)
    | ({
        relationTo: 'courses'
        value: number | Course
      } | null)
    | ({
        relationTo: 'services'
        value: number | Service
      } | null)
  itemType?: ('product' | 'course' | 'service') | null
  creemProductId?: string | null
  /**
   * Idempotency key (Creem order id).
   */
  provider?: ('creem' | 'whop') | null
  creemOrderId?: string | null
  whopPaymentId?: string | null
  /**
   * Retainers only. Ties every renewal row back to one subscription.
   */
  creemSubscriptionId?: string | null
  /**
   * Retainers only. The individual payment inside a subscription. Separate from creemOrderId because the first payment arrives twice: once as checkout.completed with an order id, once as subscription.paid with a transaction id. Keying renewals on this is what stops that first payment being banked as two sales.
   */
  creemTransactionId?: string | null
  /**
   * Cents, as Creem sends them. 0 means a free claim.
   */
  amount?: number | null
  currency?: string | null
  /**
   * Boilerplate orders — consumed by Phase B3.
   */
  githubUsername?: string | null
  /**
   * The id we minted when creating the checkout, echoed back by Creem on the webhook. It is how the post-payment onboarding page finds this row from a signed return URL, so it must stay indexed.
   */
  creemRequestId?: string | null
  /**
   * Issued by Creem, when the product has license keys enabled. Empty means the order issued none, not that one went missing.
   */
  licenseKey?: string | null
  /**
   * owner/repo the invitation was sent to, copied from the product at purchase time. Stored rather than looked up, so a later catalogue edit cannot rewrite the history of what someone bought.
   */
  githubRepo?: string | null
  /**
   * GitHub accept link. Empty means no invitation was sent — that order needs one by hand.
   */
  githubInviteUrl?: string | null
  /**
   * Every GitHub account this licence has granted, including the purchaser. The length is the seats used; the limit lives on the product. Rows are appended, never replaced, so removing someone here does not take their repository access away — do that on GitHub.
   */
  seatMembers?:
    | {
        githubUsername: string
        inviteUrl?: string | null
        addedAt?: string | null
        id?: string | null
      }[]
    | null
  accessTokenJti?: string | null
  status?: ('paid' | 'refunded') | null
  /**
   * Retainers only. Empty on one-time purchases.
   */
  subscriptionStatus?:
    | (
        | 'trialing'
        | 'active'
        | 'paid'
        | 'past_due'
        | 'scheduled_cancel'
        | 'canceled'
        | 'expired'
      )
    | null
  fulfillmentStatus?:
    | ('pending' | 'pending_invite' | 'sent' | 'failed' | 'not_required')
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number
  document?:
    | ({
        relationTo: 'users'
        value: number | User
      } | null)
    | ({
        relationTo: 'media'
        value: number | Media
      } | null)
    | ({
        relationTo: 'articles'
        value: number | Article
      } | null)
    | ({
        relationTo: 'projects'
        value: number | Project
      } | null)
    | ({
        relationTo: 'products'
        value: number | Product
      } | null)
    | ({
        relationTo: 'courses'
        value: number | Course
      } | null)
    | ({
        relationTo: 'lessons'
        value: number | Lesson
      } | null)
    | ({
        relationTo: 'services'
        value: number | Service
      } | null)
    | ({
        relationTo: 'contact-submissions'
        value: number | ContactSubmission
      } | null)
    | ({
        relationTo: 'purchases'
        value: number | Purchase
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: number | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number
  user: {
    relationTo: 'users'
    value: number | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
  sessions?:
    | T
    | {
        id?: T
        createdAt?: T
        expiresAt?: T
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T
  slug?: T
  slugLock?: T
  publishedDate?: T
  author?: T
  description?: T
  keywords?:
    | T
    | {
        keyword?: T
        id?: T
      }
  canonical?: T
  ogImage?: T
  coverImage?: T
  content?: T
  mdxSlug?: T
  status?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T
  description?: T
  link?:
    | T
    | {
        url?: T
        label?: T
      }
  logo?: T
  order?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T
  slug?: T
  slugLock?: T
  type?: T
  tagline?: T
  stack?: T
  tier?: T
  popular?: T
  pricingHighlights?:
    | T
    | {
        highlight?: T
        id?: T
      }
  description?: T
  features?:
    | T
    | {
        feature?: T
        id?: T
      }
  techStack?:
    | T
    | {
        tech?: T
        id?: T
      }
  creemProductId?: T
  price?: T
  seats?: T
  currency?: T
  priceLabel?: T
  heroImage?: T
  ogImage?: T
  gallery?:
    | T
    | {
        image?: T
        id?: T
      }
  githubRepo?: T
  demoUrl?: T
  downloadFile?: T
  downloadUrl?: T
  featured?: T
  order?: T
  status?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T
  slug?: T
  slugLock?: T
  summary?: T
  description?: T
  coverImage?: T
  level?: T
  creemProductId?: T
  price?: T
  featured?: T
  order?: T
  status?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T
  slug?: T
  slugLock?: T
  course?: T
  module?: T
  order?: T
  content?: T
  videoUrl?: T
  durationMinutes?: T
  isPreview?: T
  status?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T
  slug?: T
  slugLock?: T
  summary?: T
  description?: T
  icon?: T
  startingPrice?: T
  priceLabel?: T
  commitment?: T
  bookingUrl?: T
  depositNote?: T
  creemProductId?: T
  whopPlanId?: T
  depositAmount?: T
  order?: T
  status?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T
  email?: T
  subject?: T
  message?: T
  status?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchases_select".
 */
export interface PurchasesSelect<T extends boolean = true> {
  email?: T
  item?: T
  itemType?: T
  creemProductId?: T
  provider?: T
  creemOrderId?: T
  whopPaymentId?: T
  creemSubscriptionId?: T
  creemTransactionId?: T
  amount?: T
  currency?: T
  githubUsername?: T
  creemRequestId?: T
  licenseKey?: T
  githubRepo?: T
  githubInviteUrl?: T
  seatMembers?:
    | T
    | {
        githubUsername?: T
        inviteUrl?: T
        addedAt?: T
        id?: T
      }
  accessTokenJti?: T
  status?: T
  subscriptionStatus?: T
  fulfillmentStatus?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-page".
 */
export interface PricingPage {
  id: number
  /**
   * Small label above the heading.
   */
  eyebrow?: string | null
  heading?: string | null
  intro?: string | null
  /**
   * Small print under the table. Anything quoted here is also what Creem is told during merchant verification — keep them together.
   */
  footnote?: string | null
  faqs?:
    | {
        question: string
        answer: string
        id?: string | null
      }[]
    | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-page_select".
 */
export interface PricingPageSelect<T extends boolean = true> {
  eyebrow?: T
  heading?: T
  intro?: T
  footnote?: T
  faqs?:
    | T
    | {
        question?: T
        answer?: T
        id?: T
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown
  }
  width: 'full'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
